### ISSUE TITLE
Build broken

### ISSUE THREAD

**Issue by hfiguiere** [flathub/org.libvips.vipsdisp#1]
The build on master is broken as I write this.

Note: you can avoid thse by making update as a PR. A test build will automatically be done.

The error: https://buildbot.flathub.org/#/builders/8/builds/12802
```
Error loading desktop file: Failed to find icon: Failed to find icon org.libvips.vipsdisp
Error: ERROR: appstream-compose failed: Child process exited with code 1
```

**Comment by jcupitt** [comment]
Hi, I was struggling to make it work with meson :( It should be working now.
